server:
  port: 8080

spring:
  application:
    name: "accounts"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8888/"
  datasource: # after, this will be written by Kubernates envs
    url: jdbc:mysql://localhost:3306/sbdb-db-accounts
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"